# test-spike-keeper.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: spike
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spike-keeper
  namespace: spike
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spike-keeper-test
  namespace: spike
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spike-keeper
      app.kubernetes.io/component: keeper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spike-keeper
        app.kubernetes.io/component: keeper
        app.kubernetes.io/part-of: spike
    spec:
      serviceAccountName: spike-keeper
      containers:
        - name: test
          image: busybox
          command: ["sleep", "3600"]