#    \\ SPIKE: Secure your secrets with SPIFFE.
#  \\\\\ Copyright 2024-present SPIKE contributors.
# \\\\\\\ SPDX-License-Identifier: Apache-2.0

# SPIRE Helm Charts
# See https://github.com/spiffe/helm-charts-hardened for documentation
# and configuration options.

# `values.yaml`, but pointing to a local container registry instead of the
# upstream SPIFFE `helm-charts-hardened` registry.

spike-keeper:
  enabled: true
  image:
    registry: localhost:5000
    repository: spike-keeper
    pullPolicy: IfNotPresent
    tag: "dev"

spike-nexus:
  enabled: true
  image:
    registry: localhost:5000
    repository: spike-nexus
    pullPolicy: IfNotPresent
    tag: "dev"

spike-pilot:
  enabled: true
  image:
    registry: localhost:5000
    repository: spike-pilot
    pullPolicy: IfNotPresent
    tag: "dev"

spire-server:
  enabled: true

spire-agent:
  enabled: true

spiffe-csi-driver:
  enabled: true

spiffe-oidc-discovery-provider:
  enabled: true
