#    \\ SPIKE: Secure your secrets with SPIFFE.
#  \\\\\ Copyright 2024-present SPIKE contributors.
# \\\\\\\ SPDX-License-Identifier: Apache-2.0

global:
  openshift: false # If running on openshift, set to true
  spire:
    recommendations:
      enabled: true
    namespaces:
      create: true
    clusterName: spike-demo-cluster
    trustDomain: spike.ist
    caSubject:
      country: US
      organization: SPIKE
      commonName: spike.ist

## Add the controller manager configuration under the spire-server subchart
#spire-server:
#  controllerManager:
#    enabled: true
#    ignoreNamespaces:
#      - kube-system
#      - kube-public
#      - kube-node-lease
#      - spire-system
##      - spike-control
##      - spike-edge
##      - spike-system
##      - spike-demo

    # If you want to restrict by pod selector instead
    # identities:
    #   clusterSPIFFEIDs:
    #     default:
    #       enabled: true
    #       spiffeIDTemplate: spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}
    #       podSelector:
    #         matchLabels:
    #           spiffe.io/register: "true"  # Only pods with this label will get automatic SPIFFE IDs


#  helm upgrade --install -n spire-mgmt spire-crds spire-crds --repo https://spiffe.github.io/helm-charts-hardened/ --create-namespace
#  helm upgrade --install -n spire-mgmt spire spire --repo https://spiffe.github.io/helm-charts-hardened/ -f your-values.yaml