#    \\ SPIKE: Secure your secrets with SPIFFE.
#  \\\\\ Copyright 2024-present SPIKE contributors.
# \\\\\\\ SPDX-License-Identifier: Apache-2.0

# SPIRE Helm Charts
# See https://github.com/spiffe/helm-charts-hardened for documentation
# and configuration options.

global:
  openshift: false # If running on openshift, set to true
  spire:
    recommendations:
      enabled: true
    namespaces:
      create: true
    clusterName: spiffe
    trustDomain: spike.ist
    caSubject:
      country: US
      organization: SPIKE
      commonName: spike.ist

spike-keeper:
  enabled: true
  namespaceOverride: spike
  # TODO: replace it with localhost; I need to test it with recent local images.
  image:
    registry: ghcr.io
    repository: spiffe/spike-keeper
    pullPolicy: IfNotPresent
    tag: ""

spike-nexus:
  enabled: true
  namespaceOverride: spike
  # TODO: replace it with localhost; I need to test it with recent local images.
  image:
    registry: ghcr.io
    repository: spiffe/spike-keeper
    pullPolicy: IfNotPresent
    tag: ""

spike-pilot:
  enabled: true
  namespaceOverride: spike
  # TODO: replace it with localhost; I need to test it with recent local images.
  image:
    registry: ghcr.io
    repository: spiffe/spike-keeper
    pullPolicy: IfNotPresent
    tag: ""

spire-server:
  enabled: true

  controllerManager:
    identities:
      clusterSPIFFEIDs:
        spike-keeper:
          type: raw
          enabled: true
          spiffeIDTemplate: spiffe://{{ .TrustDomain }}/spike/keeper/{{ .PodMeta.Name }}
          namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - spike
        spike-nexus:
          type: raw
          enabled: true
          spiffeIDTemplate: spiffe://{{ .TrustDomain }}/spike/nexus/{{ .PodMeta.Name }}
          namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - spike
        spike-pilot:
          type: raw
          enabled: true
          spiffeIDTemplate: spiffe://{{ .TrustDomain }}/spike/pilot/role/superuser
          namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - spike

spire-agent:
  enabled: true

spiffe-csi-driver:
  enabled: true

spiffe-oidc-discovery-provider:
  enabled: true
