#    \\ SPIKE: Secure your secrets with SPIFFE.
#  \\\\\ Copyright 2024-present SPIKE contributors.
# \\\\\\\ SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: spike-nexus-headless
spec:
  clusterIP: None
  selector:
    app: spike-keeper
  ports:
    - port: 8553
